---
- hosts: all
 


   tasks: 
    - name: building docker image
      command: "docker build -t simple-devops-image ."
      args:
       chdir: /opt/docker
       #    - name: creating docker container using simple-devops-image
       #     command: docker run -d -- name simple-devops-container -p 8080:8080 simple-devops-image 
