---
- hosts: all
  become: true
  tasks: 
  - name: create a docker iamge using warfile
    command: docker build -t simple-devops-image:latest .
    args:
     chdir: /opt/docker
  - name: create a tag to image
    command: docker tag simple-devops-image rasheed27/simple-devops-image
  - name: push image on to docker hub
    command: docker push rasheed27/simple-devops-image
  - name: remove a docker from ansible-server
    command: docker rmi simple-devops-image:latest rasheed27/simple-devops-image
    ignore_errors: yes